# This file was generated by GoReleaser. DO NOT EDIT.
cask "rote" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "74d7602a14fa35dfdae25b11c8b0ff854365cfd8c375df990d2a1977c2b6f733"
      url "https://github.com/zhh2001/rote/releases/download/v#{version}/rote_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7a5ee8a2184b952dc337ddeeea9543de1d92dd80f00a96bf5be93de059134526"
      url "https://github.com/zhh2001/rote/releases/download/v#{version}/rote_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "60d32ae85910478821c28973ae4f2ae29acde269801e85daa616bde5fee66768"
      url "https://github.com/zhh2001/rote/releases/download/v#{version}/rote_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "11c138556b686c8f7225b3dbbad220d48e94b0e6653239db868baf8b9538c1ea"
      url "https://github.com/zhh2001/rote/releases/download/v#{version}/rote_Linux_arm64.tar.gz"
    end
  end

  name "rote"
  desc "A cron that remembers what it did."
  homepage "https://github.com/zhh2001/rote"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rote"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rote"]
    end
  end

  # No zap stanza required

end
