# This file was generated by GoReleaser. DO NOT EDIT.
cask "rote" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "05388b3c237b0369e84abab6c0e27ffd89c8e968f25ff88daa0f656add632b3a"
      url "https://github.com/zhh2001/rote/releases/download/v#{version}/rote_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7b10afd436adf314e6787b241fae909a55067aa80197a7125dcb63819b071c8b"
      url "https://github.com/zhh2001/rote/releases/download/v#{version}/rote_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ebe44a776043b5e415e7368bb0b3f331ed2f0e7d34e0be296a5bc92d072b6117"
      url "https://github.com/zhh2001/rote/releases/download/v#{version}/rote_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7bcfdb8a7e5553cd4425cfebe651c438670a22a8fcad79c488802a363e09a260"
      url "https://github.com/zhh2001/rote/releases/download/v#{version}/rote_Linux_arm64.tar.gz"
    end
  end

  name "rote"
  desc "A cron that remembers what it did."
  homepage "https://github.com/zhh2001/rote"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rote"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rote"]
    end
  end

  # No zap stanza required

end
