# This file was generated by GoReleaser. DO NOT EDIT.
cask "rote" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "ee8b37bffc57dd4b4e64f61914f4ac3a0a6c212b9c8e73c7dbb5c8d43721ce4b"
      url "https://github.com/zhh2001/rote/releases/download/v#{version}/rote_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8631f79e69a49226ea875b62f7d999af616356cf8757c4601642ca4dfe4c1e61"
      url "https://github.com/zhh2001/rote/releases/download/v#{version}/rote_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ade3c54314b0e83cb0db7cbfc1aaa47d2ec6c16851f7358988ec8e98f00fff95"
      url "https://github.com/zhh2001/rote/releases/download/v#{version}/rote_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7ec7789b34504fd10b947bdf45c1c6249fb31b4fda692499306aa9ec59d838e7"
      url "https://github.com/zhh2001/rote/releases/download/v#{version}/rote_Linux_arm64.tar.gz"
    end
  end

  name "rote"
  desc "A cron that remembers what it did."
  homepage "https://github.com/zhh2001/rote"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rote"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rote"]
    end
  end

  # No zap stanza required

end
